### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by PalleLC** [ksvan/node-red-contrib-verisure#5]
**Describe the bug**
When I try to run from NOTE-RED it starts writing fetching then Waiting..
Is the function only for specific country .. I have verisure from DK

**To Reproduce**
1. implement verisure alarm
2. define Config, I did not put anything in site name
3. deploy
4. activate

**Expected behavior**
Reply  from app

**Screenshots**
![verisure](https://user-images.githubusercontent.com/45243071/48865054-ac9fcd80-edce-11e8-8d3d-b10eafb1e302.JPG)

**Desktop (please complete the following information):**
 - OS: Noderedrun on windows
 - Browser Chrome
 - Node.js version
 - Node-red version 0.19.5

**Verisure specific:**
 - Country : DK
 - Types of devices, sensors : full alarm 
 - Number of devices, sensors : 6 window, 3 room 

**Additional context**

**Comment by ksvan** [comment]
Might be some issues between countries yes, Verisure has “routing groups” based on country. Could you run node red in debug mode and see if you get any additional output in the terminal that could help? Some fixes coming that should improve error output from connection issues as well...

**Comment by PalleLC** [comment]
Today it works like a charme, Sorry for the confusion.. Have not changed anything...
